<a href="https://colab.research.google.com/github/MkShaon/Machine-Learning-and-Deep-Learning/blob/main/3_1_Numpy_Complete_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy - Numerical Python
Advantages of Numpy Arrays:

*   Allows several mathematical Operations
*   Faster operations



In [ ]:
import numpy as np

List vs Numpy time taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007812999999998738


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 #np_array = np_array + 5

end_time = process_time()

print(end_time - start_time)

0.000694239999999624


# Numpy Arrays

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#Creating a 1D array
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [ ]:
#2D array
b = np.array([[1,2,3,4,],[5,6,7,8]])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
#3D array
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)
c.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

Initial Placeholders in numpy arrays

In [ ]:
#Create numpy arrays of Zeros '0'
x = np.zeros((4,5)) # 4 = row, 5 = columns
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create a numpy arrays of 1s
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Array of a particular value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#create an identity mattrix
i = np.eye(10)
print(i)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values
b = np.random.random((6,7)) #All values between 0 to 1
print(b)

[[0.76450969 0.22456121 0.51551229 0.33649875 0.54344762 0.37912926
  0.45806602]
 [0.20415345 0.94136794 0.31654557 0.56176794 0.56150542 0.06432467
  0.61172383]
 [0.18253661 0.07092884 0.53764465 0.94305019 0.82678963 0.40019896
  0.38437876]
 [0.83758035 0.09548051 0.8077729  0.83956312 0.36852669 0.1541294
  0.3953355 ]
 [0.02748211 0.71573184 0.90434169 0.20639937 0.0779983  0.94003022
  0.1266581 ]
 [0.22450434 0.56798903 0.07636087 0.63793518 0.57503249 0.29483191
  0.539452  ]]


In [ ]:
#Random integer values arrays
c = np.random.randint(10,100, (5,6))
print(c)

[[88 39 38 56 28 45]
 [12 20 93 10 39 29]
 [74 73 23 96 91 55]
 [44 38 91 88 34 78]
 [31 28 80 91 73 75]]


In [ ]:
#array of evenly spaced values --. specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
#array of evenly spaced values ---> specifying the step
e = np.arange(10,30, 5)
print(e)

[10 15 20 25]


In [ ]:
#convert a  list to a numpy array
list2 = [10,20, 30, 40, 50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[89 23 23 47 45]
 [39 50 18 42 79]
 [52 89 22 79 25]
 [59 17 37 12 80]
 [63 29 36 53 88]]


In [ ]:
#array shape
print(c.shape)

(5, 5)


In [ ]:
#number of dimension
print(c.ndim)

2


In [ ]:
#number of elements in an array
print(c.size)

25


In [ ]:
#checking the datatype of values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) #concatenate or joins two array

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10, (3,3))
b = np.random.randint(10,20, (3,3))
print(a)
print(b)

[[2 1 7]
 [6 3 7]
 [7 8 0]]
[[12 18 18]
 [19 13 12]
 [12 16 18]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[14 19 25]
 [25 16 19]
 [19 24 18]]
[[-10 -17 -11]
 [-13 -10  -5]
 [ -5  -8 -18]]
[[ 24  18 126]
 [114  39  84]
 [ 84 128   0]]
[[0.16666667 0.05555556 0.38888889]
 [0.31578947 0.23076923 0.58333333]
 [0.58333333 0.5        0.        ]]


In [ ]:
a = np.random.randint(0,10, (3,3))
b = np.random.randint(10,20, (3,3))
print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[5 4 8]
 [2 4 2]
 [7 5 6]]
[[18 14 16]
 [17 12 17]
 [12 17 15]]
[[23 18 24]
 [19 16 19]
 [19 22 21]]
[[-13 -10  -8]
 [-15  -8 -15]
 [ -5 -12  -9]]
[[ 90  56 128]
 [ 34  48  34]
 [ 84  85  90]]
[[0.27777778 0.28571429 0.5       ]
 [0.11764706 0.33333333 0.11764706]
 [0.58333333 0.29411765 0.4       ]]


Array Manupulation

In [ ]:
array = np.random.randint(0,10, (2,3))
print(array)
print(array.shape)

[[1 4 6]
 [2 1 3]]
(2, 3)


In [ ]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 2]
 [4 1]
 [6 3]]
(3, 2)


In [ ]:
array = np.random.randint(0,10, (2,3))
print(array)
print(array.shape)

[[4 1 3]
 [4 5 6]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 4]
 [1 5]
 [3 6]]
(3, 2)


In [ ]:
#reshaping a array
a = np.random.randint(0,10, (2,3))
print(a)
print(a.shape)

[[4 1 8]
 [7 5 4]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 1]
 [8 7]
 [5 4]]
(3, 2)
